# Generated by Django 3.2.5 on 2021-07-26 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_word', models.CharField(max_length=255)),
                ('translate_original_word', models.CharField(max_length=255)),
                ('transcription', models.CharField(blank=True, default='', max_length=255)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='create_date')),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-create_date',),
            },
        ),
    ]
